In [14]:
# Tic-Tac-Toe Program using random number in Python 

import numpy as np 
import random 
from time import sleep 

In [15]:
# Creates an empty board 
def create_board(): 
    return(np.array([[0, 0, 0], 
                     [0, 0, 0], 
                     [0, 0, 0]])) 

In [16]:
# Check for empty places on board 
def possibilities(board): 
    l = [] 
      
    for i in range(len(board)): 
        for j in range(len(board)): 
              
            if board[i][j] == 0: 
                l.append((i, j)) 
    return(l) 

In [17]:
# Select a random place for the player 
def random_place(board, player): 
    selection = possibilities(board) 
    current_loc = random.choice(selection) 
    board[current_loc] = player 
    return(board) 

In [18]:
# Checks whether the player has three of their marks in a horizontal row 
def row_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[x, y] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 

In [19]:
# Checks whether the player has three of their marks in a vertical row 
def col_win(board, player): 
    for x in range(len(board)): 
        win = True
          
        for y in range(len(board)): 
            if board[y][x] != player: 
                win = False
                continue
                  
        if win == True: 
            return(win) 
    return(win) 

In [20]:
# Checks whether the player has three of their marks in a diagonal row 
def diag_win(board, player): 
    win = True
    y = 0
    for x in range(len(board)): 
        if board[x, x] != player: 
            win = False
    if win: 
        return win 
    win = True
    if win: 
        for x in range(len(board)): 
            y = len(board) - 1 - x 
            if board[x, y] != player: 
                win = False
    return win 

In [21]:
# Evaluates whether there is a winner or a tie  
def evaluate(board): 
    winner = 0
      
    for player in [1, 2]: 
        if (row_win(board, player) or
            col_win(board,player) or 
            diag_win(board,player)): 
                 
            winner = player 
              
    if np.all(board != 0) and winner == 0: 
        winner = -1
    return winner 

In [22]:
# Main function to start the game 
def play_game(): 
    board, winner, counter = create_board(), 0, 1
    print(board) 
    sleep(2) 
      
    while winner == 0: 
        for player in [1, 2]: 
            board = random_place(board, player) 
            print("Board after " + str(counter) + " move") 
            print(board) 
            sleep(2) 
            counter += 1
            winner = evaluate(board) 
            if winner != 0: 
                break
    return(winner)

In [23]:
# Driver Code 
print("Winner is: " + str(play_game())) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [1 0 0]
 [0 0 0]]
Board after 2 move
[[0 0 0]
 [1 0 0]
 [0 0 2]]
Board after 3 move
[[1 0 0]
 [1 0 0]
 [0 0 2]]
Board after 4 move
[[1 0 0]
 [1 2 0]
 [0 0 2]]
Board after 5 move
[[1 0 0]
 [1 2 0]
 [0 1 2]]
Board after 6 move
[[1 0 0]
 [1 2 2]
 [0 1 2]]
Board after 7 move
[[1 0 1]
 [1 2 2]
 [0 1 2]]
Board after 8 move
[[1 2 1]
 [1 2 2]
 [0 1 2]]
Board after 9 move
[[1 2 1]
 [1 2 2]
 [1 1 2]]
Winner is: 1


In [27]:
theBoard = {'7': ' ' , '8': ' ' , '9': ' ' , 

            '4': ' ' , '5': ' ' , '6': ' ' , 

            '1': ' ' , '2': ' ' , '3': ' ' } 

 

board_keys = [] 

In [28]:
for key in theBoard: 

    board_keys.append(key) 

In [29]:
def printBoard(board): 

    print(board['7'] + '|' + board['8'] + '|' + board['9']) 

    print('-+-+-') 

    print(board['4'] + '|' + board['5'] + '|' + board['6']) 

    print('-+-+-') 

    print(board['1'] + '|' + board['2'] + '|' + board['3']) 

In [30]:
def game(): 

    turn = 'X' 

    count = 0  

    for i in range(10): 

        printBoard(theBoard) 

        print("It's your turn," + turn + ".Move to which place?") 

        move = input()         


        if theBoard[move] == ' ': 

            theBoard[move] = turn 

            count += 1 

        else: 

            print("That place is already filled.\nMove to which place?") 

            continue 


        if count >= 5: 

            if theBoard['7'] == theBoard['8'] == theBoard['9'] != ' ': # across the top 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****")                 

                break 

            elif theBoard['4'] == theBoard['5'] == theBoard['6'] != ' ': # across the middle 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break 

            elif theBoard['1'] == theBoard['2'] == theBoard['3'] != ' ': # across the bottom 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break 

            elif theBoard['1'] == theBoard['4'] == theBoard['7'] != ' ': # down the left side 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break 

            elif theBoard['2'] == theBoard['5'] == theBoard['8'] != ' ': # down the middle 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break 

            elif theBoard['3'] == theBoard['6'] == theBoard['9'] != ' ': # down the right side 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break  

            elif theBoard['7'] == theBoard['5'] == theBoard['3'] != ' ': # diagonal 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break 

            elif theBoard['1'] == theBoard['5'] == theBoard['9'] != ' ': # diagonal 

                printBoard(theBoard) 

                print("\nGame Over.\n")                 

                print(" **** " +turn + " won. ****") 

                break  
        if count == 9: 

            print("\nGame Over.\n")                 

            print("It's a Tie!!") 

        if turn =='X': 

            turn = 'O' 

        else: 

            turn = 'X'         

    restart = input("Do want to play Again?(y/n)") 

    if restart == "y" or restart == "Y":   

        for key in board_keys: 

            theBoard[key] = " " 

        game() 

In [31]:
if __name__ == "__main__": 

    game() 

 | | 
-+-+-
 | | 
-+-+-
 | | 
It's your turn,X.Move to which place?
3
 | | 
-+-+-
 | | 
-+-+-
 | |X
It's your turn,O.Move to which place?
2
 | | 
-+-+-
 | | 
-+-+-
 |O|X
It's your turn,X.Move to which place?
9
 | |X
-+-+-
 | | 
-+-+-
 |O|X
It's your turn,O.Move to which place?
1
 | |X
-+-+-
 | | 
-+-+-
O|O|X
It's your turn,X.Move to which place?
6
 | |X
-+-+-
 | |X
-+-+-
O|O|X

Game Over.

 **** X won. ****
Do want to play Again?(y/n)n
